'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import {
  Copy,
  Check,
  Download,
  Bookmark,
  ArrowLeft,
  RefreshCcw,
  Terminal,
  PartyPopper,
} from 'lucide-react'
import { useWorkflow } from '@/lib/workflow/context'
import { addFavorite, cacheSpec } from '@/lib/favorites'
import type { BuildSpec, ProductIdea } from '@/lib/types'
import StepProgress from '@/components/StepProgress'

function specToMarkdown(spec: BuildSpec): string {
  const lines: string[] = [
    `# ${spec.productName} -- Build Spec`,
    '',
    '## What You\'re Building',
    '', spec.whatYoureBuilding, '',
    '## Who Wants This and Why',
    '', spec.whoWantsThis, '',
    '## Why This Could Work',
    '', spec.whyThisCouldWork, '',
  ]

  if (spec.monetizationModel) {
    lines.push('## How It Makes Money', '', spec.monetizationModel, '')
  }
  if (spec.pricingStrategy) {
    lines.push('## Pricing Strategy', '', spec.pricingStrategy, '')
  }
  if (spec.revenueTimeline) {
    lines.push('## Revenue Timeline', '', spec.revenueTimeline, '')
  }
  if (spec.customerAcquisition) {
    lines.push('## Getting Customers', '', spec.customerAcquisition, '')
  }

  lines.push(
    '## Core Features (MVP Only)',
    '', ...spec.coreFeatures.map((f) => `- ${f}`), '',
    '## Tech Stack',
    '', ...spec.techStack.map((t) => `- **${t.tool}** -- ${t.why}`), '',
    '## Build Plan',
    '', ...spec.buildPlan.map((s, i) => `${i + 1}. ${s}`), '',
    '## What V2 Looks Like',
    '', ...spec.v2Ideas.map((v) => `- ${v}`), '',
    '## Honest Risks',
    '', ...spec.risks.map((r) => `- ${r}`), '',
    `**Estimated complexity:** ${spec.complexity}`,
    '', '---', '',
    'Generated by Cash Cow. Paste this into Claude Code and start building.',
  )

  return lines.join('\n')
}

export default function ExportPage() {
  const router = useRouter()
  const { state, setStep, reset } = useWorkflow()

  const [copied, setCopied] = useState(false)
  const [saved, setSaved] = useState(false)

  useEffect(() => {
    setStep(4)
  }, [setStep])

  useEffect(() => {
    if (!state.spec) {
      router.push('/workflow')
    }
  }, [state.spec, router])

  if (!state.spec) return null

  const spec = state.spec
  const markdown = specToMarkdown(spec)

  async function handleCopy() {
    await navigator.clipboard.writeText(markdown)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  function handleDownload() {
    const blob = new Blob([markdown], { type: 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${spec.productName.toLowerCase().replace(/\s+/g, '-')}-spec.md`
    a.click()
    URL.revokeObjectURL(url)
  }

  function handleSave() {
    // Convert spec to a ProductIdea shape for favorites
    const idea: ProductIdea = {
      id: `workflow-${Date.now()}`,
      name: spec.productName,
      pitch: spec.whatYoureBuilding,
      category: state.selectedProduct?.topics?.[0] || 'SaaS',
      whyNow: spec.whyThisCouldWork,
      risk: spec.risks[0] || '',
      complexity: spec.complexity,
    }
    addFavorite(idea)
    cacheSpec(idea.id, spec)
    setSaved(true)
  }

  function handleStartOver() {
    reset()
    router.push('/workflow')
  }

  return (
    <div className="min-h-screen" style={{ background: 'var(--cream)' }}>
      <div className="px-4 sm:px-6 pt-6 pb-16">
        <div className="max-w-2xl mx-auto">
          {/* Progress */}
          <div className="mb-8">
            <StepProgress current={4} />
          </div>

          {/* Back */}
          <button
            onClick={() => router.push('/workflow/spec')}
            className="inline-flex items-center gap-1.5 text-sm font-bold mb-6"
            style={{ color: 'var(--brown-muted)' }}
          >
            <ArrowLeft size={14} />
            Back to spec
          </button>

          {/* Celebration header */}
          <div className="animate-in text-center mb-8">
            <div
              className="inline-flex items-center justify-center w-16 h-16 rounded-2xl mb-4"
              style={{
                background: 'var(--cash)',
                boxShadow: '0 8px 32px rgba(34, 197, 94, 0.3)',
              }}
            >
              <PartyPopper size={32} color="#fff" />
            </div>
            <h1
              className="text-3xl sm:text-4xl font-black mb-2 tracking-tight"
              style={{ fontFamily: 'var(--font-fredoka), sans-serif' }}
            >
              Your spec is ready
            </h1>
            <p className="text-sm sm:text-base max-w-md mx-auto" style={{ color: 'var(--brown-muted)' }}>
              <span className="font-bold">{spec.productName}</span> -- a monetization-focused build plan ready to paste into your AI coding tool.
            </p>
          </div>

          {/* Action buttons */}
          <div className="animate-in space-y-3 mb-8" style={{ animationDelay: '0.1s' }}>
            {/* Copy */}
            <button
              onClick={handleCopy}
              className="btn-hover w-full flex items-center gap-3 px-5 py-4 rounded-2xl text-left"
              style={{
                background: 'var(--cash)',
                color: '#fff',
                boxShadow: '0 4px 16px rgba(34, 197, 94, 0.25)',
              }}
            >
              {copied ? <Check size={20} /> : <Copy size={20} />}
              <div>
                <p className="font-bold">{copied ? 'Copied!' : 'Copy as Markdown'}</p>
                <p className="text-xs opacity-80">Paste straight into Claude Code, Cursor, or any AI tool</p>
              </div>
            </button>

            {/* Download */}
            <button
              onClick={handleDownload}
              className="btn-hover w-full flex items-center gap-3 px-5 py-4 rounded-2xl text-left card"
            >
              <Download size={20} style={{ color: 'var(--brown-muted)' }} />
              <div>
                <p className="font-bold">Download as .md</p>
                <p className="text-xs" style={{ color: 'var(--brown-muted)' }}>
                  Save to your project folder
                </p>
              </div>
            </button>

            {/* Save to favorites */}
            <button
              onClick={handleSave}
              disabled={saved}
              className="btn-hover w-full flex items-center gap-3 px-5 py-4 rounded-2xl text-left card disabled:opacity-60"
            >
              <Bookmark
                size={20}
                style={{ color: saved ? 'var(--cash)' : 'var(--brown-muted)' }}
                fill={saved ? 'var(--cash)' : 'none'}
              />
              <div>
                <p className="font-bold">{saved ? 'Saved to your build queue' : 'Save to favorites'}</p>
                <p className="text-xs" style={{ color: 'var(--brown-muted)' }}>
                  Come back to it from the Saved page
                </p>
              </div>
            </button>
          </div>

          {/* Start building guide */}
          <div
            className="animate-in card rounded-2xl overflow-hidden mb-6"
            style={{ animationDelay: '0.15s' }}
          >
            <div
              className="px-5 py-4 flex items-center gap-2"
              style={{ background: 'var(--brown)', color: 'var(--cream)' }}
            >
              <Terminal size={16} style={{ color: 'var(--cash-light)' }} />
              <span className="text-sm font-bold">Start building right now</span>
            </div>
            <div className="p-5 space-y-3">
              <ol className="space-y-3 text-sm">
                <li className="flex items-start gap-3">
                  <span
                    className="flex-shrink-0 w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold"
                    style={{ background: 'var(--cash-soft)', color: 'var(--cash-dark)' }}
                  >
                    1
                  </span>
                  <span style={{ color: 'var(--brown-light)' }}>
                    Open your terminal. Run{' '}
                    <code
                      className="px-1.5 py-0.5 rounded text-xs font-bold"
                      style={{ background: 'var(--cream-dark)' }}
                    >
                      npx create-next-app@latest {spec.productName.toLowerCase().replace(/\s+/g, '-')}
                    </code>
                  </span>
                </li>
                <li className="flex items-start gap-3">
                  <span
                    className="flex-shrink-0 w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold"
                    style={{ background: 'var(--cash-soft)', color: 'var(--cash-dark)' }}
                  >
                    2
                  </span>
                  <span style={{ color: 'var(--brown-light)' }}>
                    Click &quot;Copy as Markdown&quot; above and paste the spec into Claude Code.
                  </span>
                </li>
                <li className="flex items-start gap-3">
                  <span
                    className="flex-shrink-0 w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold"
                    style={{ background: 'var(--cash-soft)', color: 'var(--cash-dark)' }}
                  >
                    3
                  </span>
                  <span style={{ color: 'var(--brown-light)' }}>
                    Follow the build plan step by step. Each step has file paths and specifics.
                  </span>
                </li>
              </ol>
            </div>
          </div>

          {/* Start over */}
          <div className="text-center">
            <button
              onClick={handleStartOver}
              className="btn-hover inline-flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-bold"
              style={{ color: 'var(--brown-muted)' }}
            >
              <RefreshCcw size={14} />
              Start over with a new idea
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
